/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class in_sangram_jni_JniAdaptor */

#ifndef _Included_in_sangram_jni_JniAdaptor
#define _Included_in_sangram_jni_JniAdaptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_sangram_jni_JniAdaptor
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_in_sangram_jni_JniAdaptor_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     in_sangram_jni_JniAdaptor
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_in_sangram_jni_JniAdaptor_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     in_sangram_jni_JniAdaptor
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_sangram_jni_JniAdaptor_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     in_sangram_jni_JniAdaptor
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_in_sangram_jni_JniAdaptor_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
